### ISSUE TITLE
code fails with Debian/Stretch Scribus 1.4.5

### ISSUE THREAD

**Issue by garydale** [kaleworsley/formatxml-scribus#1]
I maintain a directory of Lions Clubs in an XML file (see http://www.a711lions.ca/clubs.xml). I'm now asked to produce a printed district directory showing, among other things, the same information just formatted for print. I am trying to use formatxml-scribus to do that.

My initial attempt was to cut and paste the code I found on the scribus wiki but that didn't work for me. When I located your version on github, I gave it a try with much better results. I got the dialogues that asked for the various files and got one line of text added to the scribus document. This was the name of the first club, which was the first leaf element in the XML file. 

At that point the program crashed with the error:
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "/home/garydale/mnt2/webpages/Lions Clubs/A711/formatxml-scribus-master/formatxml.py", line 179, in <module>
    main_wrapper()
  File "/home/garydale/mnt2/webpages/Lions Clubs/A711/formatxml-scribus-master/formatxml.py", line 165, in main_wrapper
    main()
  File "/home/garydale/mnt2/webpages/Lions Clubs/A711/formatxml-scribus-master/formatxml.py", line 151, in main
    format (xml_file, template, document)
  File "/home/garydale/mnt2/webpages/Lions Clubs/A711/formatxml-scribus-master/formatxml.py", line 136, in format
    p.parse(xml_file)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/home/garydale/mnt2/webpages/Lions Clubs/A711/formatxml-scribus-master/formatxml.py", line 97, in characters
    if self.styles[-1] != None and go_ahead:
IndexError: list index out of range

I've never use python myself and have no experience with Scribus scripting. This was my first attempt at using a script and I've never even considered writing one. I've validated my xml file against a couple different online validators and it checks out as OK on both.

Hoping that you can identify the problem and suggest a fix.

Thanks.

**Comment by garydale** [comment]
Hello again Kale. I gather from the lack of updates in a couple of years that formatxml isn't the top of your to-do list but it looks like it should do an important job for me if I can get it to work. Unfortunately it blows up when I do (see my post from 3 weeks ago). 

The documentation on the Scribus wiki is terse and I find it incomprehensible. As I said, I'm new to using scripts and have never even touched Python.

I've been using the xml file that I want to import to drive a Javascript application that I recently ditched and began using XSL instead. I can get the XSL to produce the output in the form I want in a web browser (see http://www.a711lions.ca/clubs.xml), but I need to do better to get the print version ready. That's why I want to do this in Scribus.

Can you suggest what may be causing the error?

Also, the xml file has some structure to it, as you'll see if you look at the web page I mentioned above - each club has some optional information and at most 4 officers, each with their own optional information. There may be multiple occurrences of some of the information (e.g. multiple address lines or telephone numbers).

Is formatXml even able to handle this?

Thanks.

**Comment by kaleworsley** [comment]
Hi @garydale,

Sorry about the delayed response. I'm setting up a Debian VM to do some testing at the moment.

I'l get back to you as soon as I can.

Kale

**Comment by garydale** [comment]
On 12/09/15 08:27 AM, Kale Worsley wrote:

> Hi @garydale https://github.com/garydale,
> 
> Sorry about the delayed response. I'm setting up a Debian VM to do 
> some testing at the moment.
> 
> I'l get back to you as soon as I can.
> 
> Kale
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/kaleworsley/formatxml-scribus/issues/1#issuecomment-139753273.

Thanks Kale. I'm trying to convert my xml file to csv to use a different 
script (Scribus Generator) to do the job right now. However this is not 
a good long-term solution - and that script also had some problems when 
I first tried it.

What I'm trying to do is produce 40 pages of a printed club directory 
from the same xml file that I use xsl to create a web page from. XML 
allows for structured data while csv doesn't. In this case, I have a 
variable number of address lines for each club, along with 4 club 
officers, each with varying numbers of telephone numbers and address lines.

Each club would be contained in a box, with the main club information 
followed by two columns of officer information within the box. I'm not 
doing a lot of formatting - going for a clean look with three font sizes 
and some fields in bold (e.g. officer's name, club name).

The online version is at http://www.a711lions.ca/clubs.xml.  The printed 
version differs by using a single column of clubs but two columns of 
officer information, including the addresses.

I'm resigned  to having to learn how to modify python scripts in order 
to get all the features I want but your script seems like the best 
starting point for next year's directory.

Thanks again.

**Comment by garydale** [comment]
Back at it again, trying to use formatxml.py to import my data. Still getting the same error that I was getting last year. Now using Debian/Stretch (testing) with Scribus 1.4.6.

Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "/home/garydale/mnt/archives/2016/Lions Club/District/Directory/formatxml.py", line 179, in <module>
    main_wrapper()
  File "/home/garydale/mnt/archives/2016/Lions Club/District/Directory/formatxml.py", line 165, in main_wrapper
    main()
  File "/home/garydale/mnt/archives/2016/Lions Club/District/Directory/formatxml.py", line 151, in main
    format (xml_file, template, document)
  File "/home/garydale/mnt/archives/2016/Lions Club/District/Directory/formatxml.py", line 136, in format
    p.parse(xml_file)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/home/garydale/mnt/archives/2016/Lions Club/District/Directory/formatxml.py", line 97, in characters
    if self.styles[-1] != None and go_ahead:
IndexError: list index out of range
